requirements.txt: unpin pymongo and ssl dependencies
Newer versions of the cryptography module (I tested v1.3.1, but probably
others) have a dependency on cffi >= 1.4.1, so this causes errors when
we've pinned to such an old cffi version.

The exact error I was getting during installation:

  error: cffi 1.1.0 is installed but cffi>=1.4.1 is required by
  set(['cryptography'])

This change fixes the error.